import Foundation
@preconcurrency import AVFoundation
import CoreMedia
import Network
import Testing
@testable import MacStreamCore

// Source-text guardrail tests: these read repo files as strings and assert
// substrings. They are quarantined here so they can be replaced with behavior
// tests over time. Do NOT add new tests of this style (see AGENTS.md).

@Test
func packageMetadataDefinesRequiredCapturePrivacyKeys() throws {
    let infoPlistURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Resources/Info.plist")
    let packageScriptURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("script/package_macos_app.sh")
    let infoPlist = try String(contentsOf: infoPlistURL, encoding: .utf8)
    let packageScript = try String(contentsOf: packageScriptURL, encoding: .utf8)

    #expect(infoPlist.contains("NSCameraUsageDescription"))
    #expect(infoPlist.contains("NSMicrophoneUsageDescription"))
    #expect(infoPlist.contains("NSAudioCaptureUsageDescription"))
    #expect(infoPlist.contains("CFBundleShortVersionString"))
    #expect(infoPlist.contains("CFBundleVersion"))
    #expect(infoPlist.contains("CFBundleIconFile"))
    #expect(packageScript.contains("Resources/Info.plist"))
    #expect(packageScript.contains("Resources/AppIcon/MacStream.icns"))
    #expect(packageScript.contains("cp \"$APP_ICON\" \"$APP_RESOURCES/MacStream.icns\""))
}

@Test
func packagingScriptsSignAppBundleWithStableIdentifier() throws {
    let runScriptURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("script/build_and_run.sh")
    let packageScriptURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("script/package_macos_app.sh")
    let runScript = try String(contentsOf: runScriptURL, encoding: .utf8)
    let packageScript = try String(contentsOf: packageScriptURL, encoding: .utf8)

    #expect(runScript.contains("BUNDLE_ID=\"com.ideaplexa.macstream\""))
    #expect(!runScript.contains("BUNDLE_ID=\"com.macstream.app\""))
    #expect(runScript.contains("Developer ID Application: Ideaplexa LLC (53P98M92V7)"))
    #expect(runScript.contains("MAC_STREAM_ENABLE_HAISHINKIT=\"${MAC_STREAM_ENABLE_HAISHINKIT:-1}\""))
    #expect(runScript.contains("MAC_STREAM_CODESIGN_IDENTITY"))
    #expect(runScript.contains("MAC_STREAM_CODESIGN_TIMESTAMP=\"${MAC_STREAM_CODESIGN_TIMESTAMP:-none}\""))
    #expect(runScript.contains("\"$ROOT_DIR/script/package_macos_app.sh\""))
    #expect(packageScript.contains("BUNDLE_ID=\"${MAC_STREAM_BUNDLE_ID:-com.ideaplexa.macstream}\""))
    #expect(packageScript.contains("MAC_STREAM_CODESIGN_IDENTITY"))
    #expect(packageScript.contains("--identifier \"$BUNDLE_ID\""))
    #expect(packageScript.contains("--options runtime --entitlements \"$app_entitlements\""))
    #expect(packageScript.contains("MacStream.AdHoc.entitlements"))
    #expect(packageScript.contains("--timestamp --sign \"$SIGN_IDENTITY\""))
    #expect(packageScript.contains("--timestamp=none --sign -"))
    #expect(packageScript.contains("--requirements \"=designated => identifier \\\"$BUNDLE_ID\\\"\""))
    #expect(packageScript.contains("/usr/bin/codesign --verify --strict --verbose=2 \"$APP_BUNDLE\""))
    #expect(packageScript.contains("xattr -cr \"$APP_BUNDLE\""))
    #expect(packageScript.contains("expected code signature identifier $BUNDLE_ID"))
    #expect(packageScript.contains("expected stable designated requirement"))
}

@Test
func capturePreflightViewOffersRelaunchForRestartScopedPermissions() throws {
    let viewURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/CapturePreflightView.swift")
    let relauncherURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Support/MacStreamRelauncher.swift")
    let viewSource = try String(contentsOf: viewURL, encoding: .utf8)
    let relauncherSource = try String(contentsOf: relauncherURL, encoding: .utf8)

    #expect(viewSource.contains("requiresRelaunchForRequiredCapturePermission"))
    #expect(viewSource.contains("!store.shouldShowSetupChecklist"))
    #expect(viewSource.contains("Label(\"Reopen MacStream\""))
    #expect(viewSource.contains("MacStreamRelauncher.relaunch()"))
    #expect(relauncherSource.contains("/usr/bin/open"))
    #expect(relauncherSource.contains("NSApplication.shared.terminate(nil)"))
}

@Test
func studioKeepsFrequentControlsInBottomDeck() throws {
    let appURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/App/MacStreamApp.swift")
    let contentURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/ContentView.swift")
    let studioURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/StudioView.swift")
    let controlURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/StudioControlPanelView.swift")
    let directorURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/DirectorPanelView.swift")
    let streamHealthURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/StreamHealthView.swift")
    let capturePreflightURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/CapturePreflightView.swift")
    let settingsURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/SettingsView.swift")
    let checklistURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/SetupChecklistView.swift")
    let destinationURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/DestinationView.swift")
    let sourceRackURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/SourceRackView.swift")
    let storeURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStreamCore/Stores/StudioStore.swift")
    let appSource = try String(contentsOf: appURL, encoding: .utf8)
    let contentSource = try String(contentsOf: contentURL, encoding: .utf8)
    let studioSource = try String(contentsOf: studioURL, encoding: .utf8)
    let controlSource = try String(contentsOf: controlURL, encoding: .utf8)
    let directorSource = try String(contentsOf: directorURL, encoding: .utf8)
    let streamHealthSource = try String(contentsOf: streamHealthURL, encoding: .utf8)
    let capturePreflightSource = try String(contentsOf: capturePreflightURL, encoding: .utf8)
    let settingsSource = try String(contentsOf: settingsURL, encoding: .utf8)
    let checklistSource = try String(contentsOf: checklistURL, encoding: .utf8)
    let destinationSource = try String(contentsOf: destinationURL, encoding: .utf8)
    let sourceRackSource = try String(contentsOf: sourceRackURL, encoding: .utf8)
    let storeSource = try String(contentsOf: storeURL, encoding: .utf8)

    let controlIndex = try #require(studioSource.range(of: "StudioControlPanelView(store: store)")?.lowerBound)
    let previewCanvasIndex = try #require(studioSource.range(of: "PreviewCanvasView(")?.lowerBound)
    let inspectorIndex = try #require(studioSource.range(of: "private struct InspectorView")?.lowerBound)
    let checklistIndex = try #require(studioSource.range(of: "SetupChecklistView(store: store)")?.lowerBound)
    let destinationIndex = try #require(studioSource.range(of: "DestinationView(store: store)")?.lowerBound)
    let previewColumnIndex = try #require(studioSource.range(of: "private struct PreviewColumnView")?.lowerBound)
    let studioRootSource = String(studioSource[..<previewColumnIndex])
    let settingsDestinationIndex = try #require(settingsSource.range(of: "Section(\"Destination\")")?.lowerBound)
    let settingsDestinationModeIndex = try #require(settingsSource.range(of: "Picker(\"Mode\", selection: destinationMode)")?.lowerBound)
    let settingsRTMPDestinationIndex = try #require(settingsSource.range(of: "if store.destination.mode == .rtmp {")?.lowerBound)
    let destinationNameIndex = try #require(settingsSource.range(of: "TextField(\"Name\"")?.lowerBound)
    let destinationServerIndex = try #require(settingsSource.range(of: "TextField(\"Server URL\"")?.lowerBound)
    let destinationSecureIndex = try #require(settingsSource.range(of: "SecureField(\"Stream key\"")?.lowerBound)

    #expect(previewColumnIndex < previewCanvasIndex)
    #expect(previewCanvasIndex < controlIndex)
    #expect(controlIndex < inspectorIndex)
    #expect(controlIndex < destinationIndex)
    #expect(controlIndex < checklistIndex)
    #expect(settingsDestinationIndex < settingsDestinationModeIndex)
    #expect(settingsDestinationModeIndex < settingsRTMPDestinationIndex)
    #expect(destinationNameIndex < destinationServerIndex)
    #expect(destinationServerIndex < destinationSecureIndex)
    #expect(studioSource.contains("@SceneStorage(\"MacStream.StudioView.isInspectorCollapsed\")"))
    #expect(studioSource.contains("InspectorRailView(store: store)"))
    #expect(studioSource.contains(".frame(width: 52)"))
    #expect(studioSource.contains(".frame(width: 372)"))
    #expect(studioSource.contains("|| hasStreamFailure"))
    #expect(studioSource.contains("&& !hasStreamFailure"))
    #expect(studioSource.contains("|| store.recordingState.isFailed"))
    #expect(studioSource.contains(".toolbar {"))
    #expect(studioSource.contains("ToolbarItem(placement: .primaryAction)"))
    #expect(studioSource.contains("isInspectorCollapsed.toggle()"))
    #expect(studioSource.contains(".animation(.snappy(duration: 0.18), value: isInspectorCollapsed)"))
    #expect(studioSource.contains("VStack(spacing: 14)"))
    #expect(studioSource.contains("InspectorTabBarView(selection: selectedTabBinding)"))
    #expect(studioSource.contains("LiveStatusPanelView(store: store)"))
    #expect(studioSource.contains("ScrollViewReader { scrollProxy in"))
    #expect(studioSource.contains(".id(InspectorPanelID.detailTop)"))
    #expect(studioSource.contains(".onChange(of: store.shouldShowSetupChecklist)"))
    #expect(studioSource.contains(".onChange(of: selectedTabRaw)"))
    #expect(studioSource.contains("scrollProxy.scrollTo(InspectorPanelID.detailTop, anchor: .top)"))
    #expect(studioSource.contains("private enum InspectorPanelID: Hashable"))
    #expect(studioSource.contains("private enum InspectorTab: String, CaseIterable, Identifiable"))
    #expect(studioSource.contains("PreviewColumnView(store: store)"))
    #expect(!studioSource.contains("DirectorPanelView(store: store)"))
    #expect(studioSource.contains("LazyVStack(alignment: .leading, spacing: 14)"))
    #expect(studioSource.contains("StudioControlPanelView(store: store)"))
    #expect(!studioSource.contains("StudioNavigationPanelView"))
    #expect(!contentSource.contains("NavigationSplitView"))
    #expect(!contentSource.contains("SidebarView(store: store)"))
    #expect(!studioRootSource.contains("store.latestSignals"))
    #expect(!studioRootSource.contains("store.effectivePerformanceMode.previewCaptureConfiguration"))
    #expect(!studioRootSource.contains("store.captureReport"))
    #expect(studioSource.contains("if store.shouldShowSetupChecklist"))
    #expect(studioSource.contains("setupDetailPanels"))
    #expect(studioSource.contains("rightSidebarPanels"))
    #expect(studioSource.contains("case .layout:"))
    #expect(studioSource.contains("case .sources:"))
    #expect(studioSource.contains("case .health:"))
    #expect(studioSource.contains("switch store.nextSetupChecklistItem?.id"))
    #expect(studioSource.contains("case .capture:"))
    #expect(studioSource.contains("case .destination:"))
    #expect(studioSource.contains("case .sources:"))
    #expect(studioSource.contains("case .scene, nil:"))
    #expect(!studioSource.contains("SetupAssistantView"))
    #expect(studioSource.contains("private struct InspectorRailView"))
    #expect(studioSource.contains("private struct InspectorTabBarView"))
    #expect(studioSource.contains(".help(isInspectorCollapsed ? \"Show sidebar\" : \"Hide sidebar\")"))
    #expect(!contentSource.contains(".toolbar"))
    #expect(controlSource.contains("ViewThatFits(in: .horizontal)"))
    #expect(controlSource.contains("private var horizontalControls"))
    #expect(controlSource.contains("private var wrappedControls"))
    #expect(!controlSource.contains("OperatorDeckSection"))
    #expect(controlSource.contains("Picker(\"Scene\", selection: sceneSelectionBinding)"))
    #expect(controlSource.contains("sceneDeckTitle(for: scene)"))
    #expect(controlSource.contains("private var sceneSelectionBinding: Binding<StudioScene.ID>"))
    #expect(controlSource.contains("ForEach(store.scenes)"))
    #expect(controlSource.contains("store.sceneSelectionBlockedReason(for: scene)"))
    #expect(controlSource.contains("store.canSelectScene(scene)"))
    #expect(controlSource.contains("store.selectScene(scene)"))
    #expect(controlSource.contains(".disabled(!store.canSelectScene(scene))"))
    #expect(controlSource.contains(".help(store.sceneSelectionBlockedReason(for: scene) ?? scene.subtitle)"))
    #expect(!controlSource.contains("Picker(\"Director Mode\", selection: $store.directorMode)"))
    #expect(controlSource.contains("controlGroup(\"Mic\", systemImage: \"waveform\")"))
    #expect(controlSource.contains("MicrophoneLevelMeterView("))
    #expect(controlSource.contains("store.startSourceMonitoring()"))
    #expect(controlSource.contains("store.stopSourceMonitoring()"))
    #expect(controlSource.contains("@AppStorage(\"performanceMode\")"))
    #expect(controlSource.contains("@AppStorage(\"outputResolution\")"))
    #expect(controlSource.contains("@AppStorage(\"outputFrameRate\")"))
    #expect(controlSource.contains("@AppStorage(\"previewRenderQuality\")"))
    #expect(controlSource.contains("Picker(\"Performance\", selection: performanceModeBinding)"))
    #expect(controlSource.contains("Picker(\"Resolution\", selection: outputResolutionBinding)"))
    #expect(controlSource.contains("Picker(\"FPS\", selection: outputFrameRateBinding)"))
    #expect(controlSource.contains("Picker(\"Preview\", selection: previewRenderQualityBinding)"))
    #expect(controlSource.contains("ForEach(StudioPerformanceMode.allCases)"))
    #expect(controlSource.contains("ForEach(StreamOutputResolution.allCases)"))
    #expect(controlSource.contains("ForEach(StreamFrameRate.allCases)"))
    #expect(controlSource.contains("ForEach(StudioPreviewRenderQuality.allCases)"))
    #expect(controlSource.contains("Menu {"))
    #expect(controlSource.contains("performanceMenuTitle"))
    #expect(controlSource.contains("store.currentOutputResolutionWidth"))
    #expect(controlSource.contains("store.currentOutputFrameRate"))
    #expect(controlSource.contains("private var performanceModeBinding: Binding<String>"))
    #expect(controlSource.contains("private var outputResolutionBinding: Binding<String>"))
    #expect(controlSource.contains("private var outputFrameRateBinding: Binding<String>"))
    #expect(controlSource.contains("private var previewRenderQualityBinding: Binding<String>"))
    #expect(controlSource.contains("performanceModeRaw = newValue"))
    #expect(controlSource.contains("outputResolutionRaw = newValue"))
    #expect(controlSource.contains("outputFrameRateRaw = newValue"))
    #expect(controlSource.contains("previewRenderQualityRaw = newValue"))
    #expect(controlSource.contains("store.updatePreferences(preferences)"))
    #expect(!controlSource.contains("var onCollapse"))
    #expect(!controlSource.contains("onCollapse()"))
    #expect(!controlSource.contains(".help(\"Hide controls\")"))
    #expect(controlSource.contains("store.startStream()"))
    #expect(controlSource.contains("store.stopStream()"))
    #expect(controlSource.contains("store.startRecording()"))
    #expect(controlSource.contains("store.stopRecording()"))
    #expect(!controlSource.contains("store.scanCaptureDevices()"))
    #expect(!controlSource.contains("store.captureReadiness.title"))
    #expect(!controlSource.contains("store.captureReadiness.detail"))
    #expect(!controlSource.contains("store.sourceSetupDetail"))
    #expect(controlSource.contains(".lineLimit(2)"))
    #expect(controlSource.contains(".fixedSize(horizontal: false, vertical: true)"))
    #expect(controlSource.contains("store.streamStartBlockedReason"))
    #expect(controlSource.contains("store.recordingStartBlockedReason"))
    #expect(controlSource.contains("primaryActionBlockerDetail"))
    #expect(controlSource.contains("exclamationmark.triangle.fill"))
    #expect(!controlSource.contains("MacStreamRelauncher.relaunch()"))
    #expect(!controlSource.contains("Label(\"Reopen MacStream\""))
    #expect(controlSource.contains("if store.recordingState == .recording { return \"Stop Rec\" }"))
    #expect(studioSource.contains("statusIcon(\"checklist.checked\""))
    #expect(controlSource.contains("return \"Check Endpoint\""))
    #expect(controlSource.contains("return \"Stop Endpoint Check\""))
    #expect(controlSource.contains("return \"Cancel Endpoint Check\""))
    #expect(controlSource.contains("return \"Stop Rec\""))
    #expect(controlSource.contains("return \"Cancel Rec\""))
    #expect(controlSource.contains(".minimumScaleFactor(0.78)"))
    #expect(controlSource.contains("Check whether the configured endpoint is reachable"))
    #expect(appSource.contains("return \"Check Endpoint\""))
    #expect(appSource.contains("return \"Stop Endpoint Check\""))
    #expect(appSource.contains("return \"Cancel Endpoint Check\""))
    #expect(appSource.contains("Window(\"MacStream\", id: \"studio\")"))
    #expect(appSource.contains("intelligenceProvider: RuleBasedLocalIntelligenceProvider()"))
    #expect(appSource.contains("@AppStorage(\"defaultSceneKind\")"))
    #expect(appSource.contains("@AppStorage(\"setupPrompt\")"))
    #expect(appSource.contains("@AppStorage(\"destinationMode\")"))
    #expect(appSource.contains("@AppStorage(\"destinationName\")"))
    #expect(appSource.contains("@AppStorage(\"sourceConfiguration\")"))
    #expect(appSource.contains("@AppStorage(\"screenCaptureTargetPreference\")"))
    #expect(appSource.contains("@Environment(\\.scenePhase)"))
    #expect(appSource.contains("applyLaunchSetupDefaultsIfNeeded()"))
    #expect(appSource.contains("applySavedDestination()"))
    #expect(appSource.contains("applySavedSourceConfiguration()"))
    #expect(appSource.contains("applySavedScreenCaptureTargetPreference()"))
    #expect(appSource.contains("store.applyLaunchSetupDefaults("))
    #expect(appSource.contains("store.applySavedSetupPrompt(newValue)"))
    #expect(appSource.contains("scheduleDestinationSave(newDestination)"))
    #expect(appSource.contains("scheduleSourceConfigurationSave(newConfiguration)"))
    #expect(appSource.contains("saveScreenCaptureTargetPreference(newTarget)"))
    #expect(appSource.contains("destinationSaveTask?.cancel()"))
    #expect(appSource.contains("sourceConfigurationSaveTask?.cancel()"))
    #expect(appSource.contains("flushPendingPersistence()"))
    #expect(appSource.contains(".onDisappear"))
    #expect(appSource.contains("guard newScenePhase != .active else { return }"))
    #expect(appSource.contains("destinationSaveTask = nil"))
    #expect(appSource.contains("sourceConfigurationSaveTask = nil"))
    #expect(appSource.contains("persistenceDebounceDuration: Duration = .milliseconds(350)"))
    #expect(appSource.contains("try? await Task.sleep(for: Self.persistenceDebounceDuration)"))
    #expect(appSource.contains("store.reportPersistenceFailure"))
    #expect(appSource.contains("SettingsView(store: store, updater: updater)"))
    #expect(directorSource.contains("private var compactDirectorPanel"))
    #expect(directorSource.contains("private func expandedDirectorPanel(for recommendation: DirectorRecommendation)"))
    #expect(directorSource.contains("Label(\"No cue pending\", systemImage: \"checkmark.circle.fill\")"))
    #expect(directorSource.contains("private var directorActionButtons"))
    #expect(directorSource.contains("store.canApplyRecommendation"))
    #expect(directorSource.contains("store.recommendationActionBlockedReason"))
    #expect(streamHealthSource.contains("Label(healthTitle, systemImage: transportSymbol)"))
    #expect(streamHealthSource.contains("case .preview:"))
    #expect(streamHealthSource.contains("\"Preview\""))
    #expect(capturePreflightSource.contains("store.scanCaptureDevices()"))
    #expect(capturePreflightSource.contains(".disabled(!store.canScanCaptureDevices)"))
    #expect(capturePreflightSource.contains("store.captureScanBlockedReason ?? \"Check capture permissions\""))
    #expect(capturePreflightSource.contains("requiresRelaunchForRequiredCapturePermission"))
    #expect(capturePreflightSource.contains("!store.shouldShowSetupChecklist"))
    #expect(capturePreflightSource.contains("Label(\"Reopen MacStream\""))
    #expect(!capturePreflightSource.contains("showDeviceDetails"))
    #expect(capturePreflightSource.contains("CapturePermissionRow.rows"))
    #expect(capturePreflightSource.contains("permissionRows(rows)"))
    #expect(!capturePreflightSource.contains("attentionDevices"))
    #expect(!capturePreflightSource.contains("deviceRows(for: attentionDevices)"))
    #expect(!capturePreflightSource.contains("DisclosureGroup"))
    #expect(!capturePreflightSource.contains("Device details"))
    #expect(!capturePreflightSource.contains("Picker(\"Screen target\""))
    #expect(settingsSource.contains("Section(\"Startup\")"))
    #expect(settingsSource.contains("@AppStorage(\"defaultSceneKind\")"))
    #expect(settingsSource.contains("Picker(\"Startup scene\""))
    #expect(settingsSource.contains("Section(\"Destination\")"))
    #expect(settingsSource.contains("Picker(\"Mode\", selection: destinationMode)"))
    #expect(settingsSource.contains("TextField(\"Name\", text: $store.destination.name)"))
    #expect(settingsSource.contains("TextField(\"Server URL\", text: rtmpServerURL)"))
    #expect(settingsSource.contains("SecureField(\"Stream key\", text: rtmpStreamKey)"))
    #expect(settingsSource.contains("private var destinationMode: Binding<StreamDestinationMode>"))
    #expect(settingsSource.contains("Section(\"Setup Rules\")"))
    #expect(settingsSource.contains("@AppStorage(\"setupPrompt\")"))
    #expect(settingsSource.contains("TextField(\"Stream description\""))
    #expect(settingsSource.contains("store.generateSetupPlan()"))
    #expect(settingsSource.contains("Section(\"Stream Behavior\")"))
    #expect(settingsSource.contains("setupPromptBinding"))
    #expect(settingsSource.contains("recordWhileStreamingBinding"))
    #expect(settingsSource.contains("preferences.recordWhileStreaming = newValue"))
    #expect(settingsSource.contains("preferences.directorCountdownSeconds = normalizedSeconds"))
    #expect(settingsSource.contains("Section(\"Output\")"))
    #expect(settingsSource.contains("Picker(\"Performance\", selection: performanceModeBinding)"))
    #expect(settingsSource.contains("@AppStorage(\"performanceMode\")"))
    #expect(settingsSource.contains("@AppStorage(\"outputResolution\")"))
    #expect(settingsSource.contains("@AppStorage(\"outputFrameRate\")"))
    #expect(settingsSource.contains("@AppStorage(\"previewRenderQuality\")"))
    #expect(storeSource.contains("public func applySavedDestination(_ savedDestination: StreamDestination)"))
    #expect(storeSource.contains("public var sourceConfiguration: [StudioSourceConfiguration]"))
    #expect(storeSource.contains("public func applySavedSourceConfiguration(_ savedConfiguration: [StudioSourceConfiguration])"))
    #expect(storeSource.contains("public private(set) var screenCaptureTargetPreference: ScreenCaptureTarget?"))
    #expect(storeSource.contains("public func applySavedScreenCaptureTargetPreference(_ target: ScreenCaptureTarget?)"))
    #expect(destinationSource.contains("Label(store.destination.safeDisplayDetail, systemImage: store.destination.mode.symbolName)"))
    #expect(destinationSource.contains("SettingsLink"))
    #expect(destinationSource.contains("Label(\"Configure\", systemImage: \"gearshape\")"))
    #expect(destinationSource.contains("destinationDetailTint"))
    #expect(!destinationSource.contains("TextField(\"Name\", text: $store.destination.name)"))
    #expect(!destinationSource.contains("SecureField(\"Stream key\""))
    #expect(storeSource.contains("public var canScanCaptureDevices"))
    #expect(storeSource.contains("captureScanBlockedReason == nil"))
    #expect(storeSource.contains("Stop preview, stream, or recording before checking capture devices."))
    #expect(storeSource.contains("!isStreamStopping"))
    #expect(storeSource.contains("!isRecordingStopping"))
    #expect(!destinationSource.contains("store.startRecording()"))
    #expect(!destinationSource.contains("store.stopRecording()"))
    #expect(!destinationSource.contains("recordingActionTitle"))
    #expect(destinationSource.contains("Last Recording"))
    #expect(checklistSource.contains("Preflight"))
    #expect(checklistSource.contains("ProgressView(value: store.setupProgressFraction)"))
    #expect(checklistSource.contains("store.nextSetupChecklistItem"))
    #expect(checklistSource.contains("SetupChecklistRow"))
    #expect(checklistSource.contains("borderedProminent"))
    #expect(checklistSource.contains("store.shouldShowSetupChecklist"))
    #expect(checklistSource.contains("store.setupChecklistItems"))
    #expect(checklistSource.contains("store.selectRecommendedStartingScene()"))
    #expect(checklistSource.contains("store.scanCaptureDevices()"))
    #expect(checklistSource.contains("MacStreamRelauncher.relaunch()"))
    #expect(checklistSource.contains("store.setDestinationMode(.preview)"))
    #expect(checklistSource.contains("store.enableRecommendedSources()"))
    #expect(checklistSource.contains("Fix Needed Sources"))
    #expect(checklistSource.contains("store.missingRequiredCapturePermissionKinds"))
    #expect(checklistSource.contains("store.promptableRequiredCapturePermissionKinds"))
    #expect(checklistSource.contains("store.blockedRequiredCapturePermissionKinds"))
    #expect(checklistSource.contains("store.missingRequiredCaptureDeviceKinds"))
    #expect(checklistSource.contains("CapturePermissionActions.requestAccess"))
    #expect(checklistSource.contains("CapturePermissionActions.openSettings(for: blockedKind)"))
    #expect(checklistSource.contains("CapturePermissionActions.openSettings(for: .display)"))
    #expect(!controlSource.contains("store.setupRole(for: source.kind)"))
    #expect(!controlSource.contains("SourceStatusRow("))
    #expect(sourceRackSource.contains(".disabled(!store.canToggleSource(source))"))
    #expect(sourceRackSource.contains(".disabled(!store.canAdjustSourceLevel(source))"))
    #expect(sourceRackSource.contains("@SceneStorage(\"MacStream.SourceRackView.showMoreSources\")"))
    #expect(sourceRackSource.contains("sourceRows(for: primarySources)"))
    #expect(sourceRackSource.contains("DisclosureGroup(isExpanded: $showMoreSources)"))
    #expect(sourceRackSource.contains("Label(\"More sources\", systemImage: \"ellipsis.circle\")"))
    #expect(sourceRackSource.contains("store.setupRole(for: source.kind)"))
    #expect(sourceRackSource.contains("case .required, .recommended:"))
    #expect(sourceRackSource.contains("case .optional, .unused:"))
    #expect(sourceRackSource.contains("sourceToggleHelp(for: source)"))
    #expect(sourceRackSource.contains("sourceLevelHelp(for: source)"))
    #expect(sourceRackSource.contains("Stop capture before turning off a source used by the current scene"))
    #expect(sourceRackSource.contains("Stop capture before adjusting a source used by the current scene"))
    #expect(sourceRackSource.contains("refreshDevicesButton"))
    #expect(sourceRackSource.contains("store.scanCaptureDevices()"))
    #expect(sourceRackSource.contains("private func deviceSelector(for kind: SourceKind)"))
    #expect(sourceRackSource.contains("store.availableCameraDevices"))
    #expect(sourceRackSource.contains("store.availableMicrophoneDevices"))
    #expect(sourceRackSource.contains("store.availableScreenCaptureTargets"))
    #expect(sourceRackSource.contains("store.selectCameraDevice(id: $0)"))
    #expect(sourceRackSource.contains("store.selectMicrophoneDevice(id: $0)"))
    #expect(sourceRackSource.contains("store.selectScreenCaptureTarget(target)"))
    #expect(sourceRackSource.contains("store.canSelectInputDevice"))
}

@Test
func screenPreviewDoesNotRequestScreenRecordingPermissionPassively() throws {
    let previewURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/NativePreview/ScreenCapturePreviewView.swift")
    let canvasURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/PreviewCanvasView.swift")
    let studioURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/StudioView.swift")
    let previewSource = try String(contentsOf: previewURL, encoding: .utf8)
    let canvasSource = try String(contentsOf: canvasURL, encoding: .utf8)
    let studioSource = try String(contentsOf: studioURL, encoding: .utf8)

    #expect(!previewSource.contains("CGRequestScreenCaptureAccess"))
    #expect(previewSource.contains("CGPreflightScreenCaptureAccess()"))
    #expect(previewSource.contains("configuration.queueDepth = previewConfiguration.queueDepth"))
    #expect(canvasSource.contains("isScreenCaptureReady"))
    #expect(canvasSource.contains("Screen Capture Not Ready"))
    #expect(studioSource.contains("isScreenCaptureReady: store.captureReport.isScreenCapturePermissionGranted"))
}

@Test
func signalSamplingDoesNotRequestScreenRecordingPermissionPassively() throws {
    let signalURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStreamCore/Services/SignalProvider.swift")
    let signalSource = try String(contentsOf: signalURL, encoding: .utf8)

    #expect(!signalSource.contains("CGRequestScreenCaptureAccess"))
    #expect(signalSource.contains("CGPreflightScreenCaptureAccess()"))
    #expect(signalSource.contains("stateQueue.async"))
    #expect(signalSource.contains("applyMonitorsForCurrentState(configuration:"))
}

@Test
func cameraPreviewDoesNotRequestCameraPermissionPassively() throws {
    let previewURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/NativePreview/CameraPreviewView.swift")
    let canvasURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/PreviewCanvasView.swift")
    let studioURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/StudioView.swift")
    let captureURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Views/CapturePreflightView.swift")
    let permissionActionsURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Support/CapturePermissionActions.swift")
    let previewSource = try String(contentsOf: previewURL, encoding: .utf8)
    let canvasSource = try String(contentsOf: canvasURL, encoding: .utf8)
    let studioSource = try String(contentsOf: studioURL, encoding: .utf8)
    let captureSource = try String(contentsOf: captureURL, encoding: .utf8)
    let permissionActionsSource = try String(contentsOf: permissionActionsURL, encoding: .utf8)

    #expect(!previewSource.contains("requestAccess"))
    #expect(previewSource.contains("authorizationStatus(for: .video)"))
    #expect(canvasSource.contains("isCameraCaptureReady"))
    #expect(canvasSource.contains("Camera Capture Not Ready"))
    #expect(studioSource.contains("isCameraCaptureReady: store.captureReport.hasGrantedPermission(for: .camera)"))
    #expect(captureSource.contains("CapturePermissionRow.rows"))
    #expect(captureSource.contains("CapturePermissionActions.requestAccess(for: row.requestKind, store: store)"))
    #expect(!captureSource.contains("CapturePermissionActions.requestAccess(for: device.kind, store: store)"))
    #expect(permissionActionsSource.contains("mediaType = .video"))
    #expect(permissionActionsSource.contains("mediaType = .audio"))
    #expect(permissionActionsSource.contains("AVCaptureDevice.requestAccess(for: mediaType)"))
}

@Test
func cameraEnhancementControlsStayWithCameraSourceAndPreviewOnly() throws {
    let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
    let modelsSource = try String(contentsOf: root.appendingPathComponent("Sources/MacStreamCore/Models/StudioModels.swift"), encoding: .utf8)
    let storeSource = try String(contentsOf: root.appendingPathComponent("Sources/MacStreamCore/Stores/StudioStore.swift"), encoding: .utf8)
    let appSource = try String(contentsOf: root.appendingPathComponent("Sources/MacStream/App/MacStreamApp.swift"), encoding: .utf8)
    let previewSource = try String(contentsOf: root.appendingPathComponent("Sources/MacStream/NativePreview/CameraPreviewView.swift"), encoding: .utf8)
    let canvasSource = try String(contentsOf: root.appendingPathComponent("Sources/MacStream/Views/PreviewCanvasView.swift"), encoding: .utf8)
    let studioSource = try String(contentsOf: root.appendingPathComponent("Sources/MacStream/Views/StudioView.swift"), encoding: .utf8)
    let sourceRackSource = try String(contentsOf: root.appendingPathComponent("Sources/MacStream/Views/SourceRackView.swift"), encoding: .utf8)

    #expect(modelsSource.contains("public struct CameraEnhancementSettings"))
    #expect(modelsSource.contains("public enum CameraPreviewRotation"))
    #expect(modelsSource.contains("cameraEnhancements: CameraEnhancementSettings = CameraEnhancementSettings()"))
    #expect(storeSource.contains("public func updateCameraEnhancements"))
    #expect(appSource.contains("@AppStorage(\"cameraEnhancementSettings\")"))
    #expect(appSource.contains("loadCameraEnhancementSettings()"))
    #expect(appSource.contains("saveCameraEnhancementSettings(newSettings)"))
    #expect(previewSource.contains("var cameraEnhancements = CameraEnhancementSettings()"))
    #expect(previewSource.contains("CIFilter(name: \"CIColorControls\")"))
    #expect(previewSource.contains("device.exposureMode = .continuousAutoExposure"))
    #expect(previewSource.contains("device.focusMode = .continuousAutoFocus"))
    #expect(previewSource.contains("device.whiteBalanceMode = .continuousAutoWhiteBalance"))
    #expect(previewSource.contains("previewLayer.setAffineTransform(transform)"))
    #expect(canvasSource.contains("cameraEnhancements: cameraEnhancements"))
    #expect(studioSource.contains("cameraEnhancements: store.preferences.cameraEnhancements"))
    #expect(sourceRackSource.contains("CameraEnhancementControls("))
    #expect(sourceRackSource.contains("Toggle(\"Mirror\""))
    #expect(sourceRackSource.contains("Toggle(\"Exposure Boost\""))
    #expect(sourceRackSource.contains("Picker(\"Rotation\""))
}

@Test
func technicalRisksSeparateSmoothMicFromVirtualMicrophoneReleasePath() throws {
    let docsURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("docs/technical-risks.md")
    let docs = try String(contentsOf: docsURL, encoding: .utf8)

    #expect(docs.contains("JoyCast-style mic polish"))
    #expect(docs.contains("selectable virtual microphone"))
    #expect(docs.contains("MacStream's MVP should first process microphone audio only inside its own recording and RTMP paths."))
    #expect(docs.contains("`AVAudioEngine` or Audio Unit graph"))
    #expect(docs.contains("before exposing a main-window Smooth Mic toggle"))
}

@Test
func packageManifestKeepsHeavyAIAndRTMPDependenciesOptIn() throws {
    let manifestURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Package.swift")
    let manifest = try String(contentsOf: manifestURL, encoding: .utf8)

    #expect(manifest.contains("MAC_STREAM_ENABLE_HAISHINKIT"))
    #expect(manifest.contains("MAC_STREAM_ENABLE_MLX"))
    #expect(manifest.contains("HaishinKit.swift"))
    #expect(manifest.contains("mlx-swift-lm"))
    #expect(manifest.contains("MLXLLM"))
    #expect(manifest.contains("MLXLMCommon"))
    #expect(manifest.contains("MLXHuggingFace"))
}

@Test
func releaseAutomationDefinesSignedNotarizedMacPipeline() throws {
    let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
    let ciURL = root.appendingPathComponent(".github/workflows/ci.yml")
    let releaseURL = root.appendingPathComponent(".github/workflows/release.yml")
    let packageScriptURL = root.appendingPathComponent("script/package_macos_app.sh")
    let dmgScriptURL = root.appendingPathComponent("script/package_macos_dmg.sh")
    let entitlementsURL = root.appendingPathComponent("Resources/Entitlements/MacStream.Release.entitlements")
    let infoPlistURL = root.appendingPathComponent("Resources/Info.plist")
    let sourceIconURL = root.appendingPathComponent("Resources/AppIcon/MacStream-AppIcon-Source.png")
    let iconURL = root.appendingPathComponent("Resources/AppIcon/MacStream.icns")
    let iconReadmeURL = root.appendingPathComponent("Resources/AppIcon/README.md")
    let docsURL = root.appendingPathComponent("docs/releasing.md")
    let ci = try String(contentsOf: ciURL, encoding: .utf8)
    let release = try String(contentsOf: releaseURL, encoding: .utf8)
    let packageScript = try String(contentsOf: packageScriptURL, encoding: .utf8)
    let dmgScript = try String(contentsOf: dmgScriptURL, encoding: .utf8)
    let entitlements = try String(contentsOf: entitlementsURL, encoding: .utf8)
    let infoPlist = try String(contentsOf: infoPlistURL, encoding: .utf8)
    let iconReadme = try String(contentsOf: iconReadmeURL, encoding: .utf8)
    let docs = try String(contentsOf: docsURL, encoding: .utf8)

    #expect(FileManager.default.fileExists(atPath: sourceIconURL.path))
    #expect(FileManager.default.fileExists(atPath: iconURL.path))
    #expect(iconReadme.contains("MacStream-AppIcon-Source.png"))
    #expect(ci.contains("runs-on: macos-26"))
    #expect(ci.contains("FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: \"true\""))
    #expect(ci.contains("swift test"))
    #expect(ci.contains("swift build -c release --arch arm64"))
    #expect(ci.contains("MAC_STREAM_REQUIRE_HARDENED_RUNTIME: \"1\""))
    #expect(ci.contains("actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6"))
    #expect(ci.contains("actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7"))
    #expect(release.contains("runs-on: macos-26"))
    #expect(release.contains("FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: \"true\""))
    #expect(release.contains("actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6"))
    #expect(release.contains("actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7"))
    #expect(release.contains("GH_REPO: ${{ github.repository }}"))
    #expect(release.contains("MAC_STREAM_MACOS_CERTIFICATE_P12_BASE64"))
    #expect(release.contains("MAC_STREAM_MACOS_CERTIFICATE_PASSWORD"))
    #expect(release.contains("MAC_STREAM_CODESIGN_IDENTITY"))
    #expect(release.contains("MAC_STREAM_APPLE_ID"))
    #expect(release.contains("MAC_STREAM_APPLE_TEAM_ID"))
    #expect(release.contains("MAC_STREAM_APP_SPECIFIC_PASSWORD"))
    #expect(release.contains("security import \"$certificate_path\""))
    #expect(release.contains("MAC_STREAM_REQUIRE_DEVELOPER_ID: \"1\""))
    #expect(release.contains("MAC_STREAM_REQUIRE_HARDENED_RUNTIME: \"1\""))
    #expect(release.contains("xcrun notarytool submit"))
    #expect(release.contains("xcrun notarytool log"))
    #expect(release.contains("xcrun stapler staple"))
    #expect(release.contains("spctl -a -vv --type execute"))
    #expect(release.contains("spctl -a -vv --type open --context context:primary-signature"))
    #expect(release.contains("steps.dmg.outputs.dmg_path"))
    #expect(release.contains("steps.dmg_checksum.outputs.dmg_sha256_path"))
    #expect(release.contains("shasum -a 256"))
    #expect(release.contains("gh release create"))
    #expect(packageScript.contains("--options runtime --entitlements \"$app_entitlements\""))
    #expect(packageScript.contains("MacStream.AdHoc.entitlements"))
    #expect(packageScript.contains("-name \"Autoupdate\""))
    #expect(packageScript.contains("CN=Developer ID Application:"))
    #expect(packageScript.contains("--extract-certificates"))
    #expect(dmgScript.contains("/usr/bin/hdiutil create"))
    #expect(dmgScript.contains("ln -s /Applications"))
    #expect(dmgScript.contains("/usr/bin/codesign"))
    #expect(dmgScript.contains("MAC_STREAM_REQUIRE_DEVELOPER_ID"))
    #expect(dmgScript.contains("CN=Developer ID Application:"))
    #expect(dmgScript.contains("--extract-certificates"))
    #expect(infoPlist.contains("CFBundleIconFile"))
    #expect(infoPlist.contains("LSApplicationCategoryType"))
    #expect(entitlements.contains("com.apple.security.device.camera"))
    #expect(entitlements.contains("com.apple.security.device.audio-input"))
    #expect(release.contains("SPARKLE_PRIVATE_KEY"))
    #expect(release.contains("\"$RUNNER_TEMP/bin/sign_update\""))
    #expect(docs.contains("Sparkle"))
}

@Test
func keychainPersistenceReportsFailuresToApp() throws {
    let keychainURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/Support/MacStreamDestinationKeychain.swift")
    let appURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStream/App/MacStreamApp.swift")
    let keychainSource = try String(contentsOf: keychainURL, encoding: .utf8)
    let appSource = try String(contentsOf: appURL, encoding: .utf8)

    #expect(keychainSource.contains("static func saveRTMPURL(_ value: String) -> Bool"))
    #expect(keychainSource.contains("static func loadRTMPURL(allowUserInteraction: Bool = false) -> String?"))
    #expect(keychainSource.contains("static func deleteRTMPURL(allowUserInteraction: Bool = false) -> Bool"))
    #expect(keychainSource.contains("context.interactionNotAllowed = true"))
    #expect(keychainSource.contains("return SecItemAdd(item as CFDictionary, nil) == errSecSuccess"))
    #expect(appSource.contains("let rtmpURL = mode == .rtmp"))
    #expect(appSource.contains("if !MacStreamDestinationKeychain.saveRTMPURL(destination.rtmpURL)"))
    #expect(appSource.contains("if !MacStreamDestinationKeychain.deleteRTMPURL()"))
    #expect(appSource.contains("store.reportPersistenceFailure"))
}

@Test
func studioStoreKeepsRuntimeStateReadOnlyOutsideStore() throws {
    let storeURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        .appendingPathComponent("Sources/MacStreamCore/Stores/StudioStore.swift")
    let source = try String(contentsOf: storeURL, encoding: .utf8)
    let readOnlyRuntimeState = [
        "streamState",
        "streamTransport",
        "recordingState",
        "lastRecordingURL",
        "health",
        "systemPressure",
        "latestSignals",
        "recommendation",
        "events",
        "clipMarkers",
        "latestClipExportURL",
        "latestSessionReportURL",
        "setupSummary",
        "isGeneratingSetupPlan",
        "isStreamStopping",
        "isRecordingStopping",
        "localIntelligenceStatus",
        "directorProfile",
        "preferences",
        "effectivePerformanceMode",
        "captureReport",
        "isScanningCapture",
        "hasRunInitialCaptureScan",
        "selectedCameraDeviceID",
        "cameraDeviceIDPreference",
        "selectedMicrophoneDeviceID",
        "microphoneDeviceIDPreference"
    ]

    for property in readOnlyRuntimeState {
        #expect(source.contains("public private(set) var \(property)"))
    }
}
